### ISSUE TITLE
Don't get sound on Ryzen 3 3200G. It shows no Output devices.

### ISSUE THREAD

**Issue by xenon86k** [elementary/switchboard-plug-sound#194]
## What Happened
There is no sound in my system. It shows no sound peripheral detected. I think it's because of the 5.8.x kernel. I had same issues before with this kernel. It would be very helpful if you guys fix this problem before releasing the stable version. Thank you!

## Platform Information
OS: Elementary OS 6 Beta
Kernel: Kernel Version: 5.80
Processor: Ryzen 3 3200G
Motherboard: A320

**Comment by ryonakano** [comment]
Hi, thank you for your reporting. Two things I want to ask you:

* I assume you might be using another motherboard than H310 because it's for Intel processors. Is it correct?
* Do you see this issue with Ubuntu 20.04 LTS which elementary OS 6 Beta is based on? If yes, it might be a hardware issue or an issue in the upstream, Ubuntu.

FYI I'm using 6 Beta with Ryzen 5 3400G (which is the same generation with Ryzen 3 3200G) and B450M motherboard by MSI and have no issue with sound.

**Comment by xenon86k** [comment]
Sorry, I wrote H310 instead of A320. My motherboard is Gigabyte A320M S2H. I've faced the same problem with Ubuntu 20.10, Kubuntu 20.10 and Pop!_OS 20.10. I didn't face any issue in Ubuntu 20.04 or 20.04 based distros. The problem is like, it detects sound peripherals first, but after sometime all sound output goes away. Then it doesn't detect any sound output. I plug/unplug my speaker but the problem stays.
Thanks for your reply!
