### ISSUE TITLE
Not all available devices are shown in the list [$50]

### ISSUE THREAD

**Issue by Philip-Scott** [elementary/switchboard-plug-sound#47]
With headphones plugged in, using `pavucontrol` you can see that there are more input devices than the ones the plug shows. Said devices did used to show up in Gnome's plug back in Loki

![image](https://user-images.githubusercontent.com/10786508/35310454-1dfce42c-0077-11e8-8c84-031860ada00a.png)

---
There is a bounty on this issue on [Bountysource](https://www.bountysource.com/issues/54146992-not-all-available-devices-are-shown-in-the-list)

**Comment by cassidyjames** [comment]
All I've ever seen is "Built-in", I can't get other devices to show up at all. That makes this pretty useless for anywhere you have an HDMI or DisplayPort external display with audio.

**Comment by cassidyjames** [comment]
@Philip-Scott is this possibly a Juno regression? I feel like this would have been reported already otherwise… :thinking:

**Comment by danrabbit** [comment]
@cassidyjames Sound plug isn't shipped in Loki. It's only available in daily there.

I can't confirm this issue using an external USB sound capture device

**Comment by ctsdownloads** [comment]
As promised, here's a video demonstrating the behavior in duplicating what is described here.

[https://www.youtube.com/embed/gIwAME8kgTU](url)

1) For output, the sound devices vanish when I do an audio test (see video) with rapid mouse clicks on the sound test speaker icons. Otherwise devices simply vanish more slowly when I select one device or another.

2) This was done using the package provided to me by Daniel.
